# Generated by Django 5.1.5 on 2025-01-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_book_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
